require("config.opt")
require('config.keymap')
require('config.pack')
require('config.lsp')
require('config.cmd')

require('config.hardtime')
require('config.lualine')
require('config.precognition')
require('config.telescope')
require('config.which-key')
