sh ~/.dotfiles/src/diff/diff-autostart.sh
sh ~/.dotfiles/src/diff/diff-dconf.sh
sh ~/.dotfiles/src/diff/diff-fastfetch-config.sh
sh ~/.dotfiles/src/diff/diff-fastfetch-output.sh
sh ~/.dotfiles/src/diff/diff-flatpak-list.sh
sh ~/.dotfiles/src/diff/diff-git-repos.sh
sh ~/.dotfiles/src/diff/diff-nala-list-installed.sh
sh ~/.dotfiles/src/diff/diff-tree.sh
sh ~/.dotfiles/src/diff/diff-vscode-extensions.sh
sh ~/.dotfiles/src/diff/diff-vscode-keybindings.sh
sh ~/.dotfiles/src/diff/diff-vscode-settings.sh
sh ~/.dotfiles/src/diff/diff-zig-version-list.sh
